<nav id="header-menu-bar" class="navbar navbar-static-top" role="navigation">
    <div id="title" class="navbar-header">
        <a href="index.php?controller=home&action=index">Example</a>
    </div>
    <ul class="nav navbar-top-links navbar-right">.
        <li>
            <a id="log-menu">
                <i class="fa fa-desktop"></i> Log
            </a>
        </li>
        <li>
            <a>
                <i class="fa fa-terminal"></i> Console
            </a>
        </li>
        <li>
            <a>
                <i class="fa fa-sign-out"></i> Log out
            </a>
        </li>
    </ul>
</nav>