<div class="gray-bg full-width full-height">
    <div id="login-form" class="middle-box text-center loginscreen animated fadeInDown">
        <div>
            <div>
            </div>
            <h3>Welcome to <br><h2>Example</h2></h3>
            <p>Please, you need login in to continue.</p>
            <form class="m-t" role="form" method="POST" action="?controller=login&action=dologin">
                <div class="form-group">
                    <input type="text" name="username" class="form-control" placeholder="Username" required="">
                </div>
                <div class="form-group">
                    <input type="password" name="password" class="form-control" placeholder="Password" required="">
                </div>
                <button type="submit" class="btn btn-primary block full-width m-b">Login</button>
            </form>
            <p class="m-t"><a href="http://www.alissonrubim.com"><h5>www.alissonrubim.com</h5></a></p>
        </div>
    </div>
</div>

