${layout: views/_shared/_layout.phtml}

<h1>Welcome to Azuul example</h1>
<small>This is a login screen</small>
<form action="index.php?controller=login&action=dologin" method="POST">
    <div><input type="text" name="username" value="" placeholder="Username"></div>
    <div><input type="password" name="password" value="" placeholder="Psername"></div>
    <input type="submit" value="Log in">
</form>
