<?php include("views/_shared/_header.phtml"); ?>

<div id="hardware-status" class="status-box middle-box">
    <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5>Hardware status</h5>
        </div>
        <div class="ibox-content">
            <div class="description">Here you can see the hardware status</div>
            <table class="table table-hover table-bordered">
                <thead>
                    <tr>
                        <th>Parameter</th>
                        <th>Value</th>
                    </tr>
                </thead>
                <tr>
                    <td>Operational System</td>
                    <td><label><?=PHP_OS?></label></td>
                </tr>
                <tr>
                    <td>Serial Number</td>
                    <td><label id="hardware-serial-number">-</label></td>   
                </tr>
                <tr>
                    <td>Model</td>
                    <td><label id="hardware-model"></label></td>   
                </tr>
                <tr>
                    <td>CPU Temperature</td>
                    <td><label id="hardware-temperature">-</label></td>
                </tr>
                <tr>
                    <td>Up Time</td>
                    <td><label  id="hardware-up-time">-</label></td>
                </tr>
                <tr>
                    <td>Memory Usage</td>
                    <td><label id="hardware-memory-usage">-</label></td>
                </tr>
                <tr>
                    <td>Disk Usage</td>
                    <td><label id="hardware-disk-usage">-</label></td>
                </tr>
                <tr>
                    <td>IP's</td>
                    <td><label id="hardware-ips">-</label></td>
                </tr>
            </table>
        </div>
    </div>
</div>
    
<div id="firmware-status" class="status-box middle-box">
    <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5>Firmware status</h5>
        </div>
        <div class="ibox-content">
            <div class="description">Here you can see the firmware status</div>
            <table class="table table-hover table-bordered">
                <thead>
                    <tr>
                        <th>Parameter</th>
                        <th>Value</th>
                    </tr>
                </thead>
                <tr>
                    <td>Version</td>
                    <td><label id="firmware-version"></label></td>
                </tr>
            </table>
        </div>
    </div>
</div>

<div id="wifi-status" class="status-box middle-box">
    <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5>Wifi status</h5>
        </div> 
        <div class="ibox-content">
            <div class="description">Here you can see the wifi status</div>
        </div>
    </div>
</div>

<div id="thermal-status" class="status-box middle-box">
    <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5>Thermal printers</h5>
        </div> 
        <div class="ibox-content">
            <div class="description">Here you can see all the conected thermal printers</div>
            <!--<table class="table table-hover table-bordered">
                <thead>
                    <tr>
                        <th colspan="2">Thermal Printer 01</th>
                    </tr>
                    <tr>
                        <th>Parameter</th>
                        <th>Value</th>
                    </tr>
                </thead>
                <tr>
                    <td>Interface</td>
                    <td><label>/dev/lp0</label></td>
                </tr>
                <tr>
                    <td>Name</td>
                    <td><label >-</label></td>
                </tr>
                <tr>
                    <td>Fabricant</td>
                    <td><label >-</label></td>
                </tr>
                <tr>
                    <td>Serial Identifier</td>
                    <td><label >-</label></td>
                </tr>
            </table>-->
        </div>
    </div>
</div>


<!--<div class="col-lg-6">
    <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5>Ethernet status</h5>
        </div>
        <div class="ibox-content">
        	<table class="table">
				<tr>
					<td>Status</td>
					<td><label>#NOT_IMPLEMENTED#</label></td>
				</tr>
				<tr>
					<td>MacAddress</td>
					<td><label>#NOT_IMPLEMENTED#</label></td>
				</tr>
				<tr>
					<td>IP</td>
					<td><label>#NOT_IMPLEMENTED#</label></td>
				</tr>
			</table>
        </div>
    </div>
</div>


<div class="col-lg-12">
    <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5>Power</h5>
        </div>
        <div class="ibox-content">
        	<p>
                Up Time: <label>#NOT_IMPLEMENTED#</label>
            </p>
            <p>
                Use this buttons to controll the system power
            </p>
            <button type="button" class="btn btn-rounded btn-warning"><i class="fa fa-refresh"> Restart #NOT_IMPLEMENTED#</i></button>
			<button type="button" class="btn btn-rounded btn-danger"><i class="fa fa-circle-o-notch"> Shutdown #NOT_IMPLEMENTED#</i></button>
        </div>
    </div>
</div>-->

<script type="text/javascript">
    $(document).ready(function(){
        EWBox.HardwareStatus();
        EWBox.FirmwareStatus();
        EWBox.WifiStatus();
    })
</script>